[package]
name = "stratamoto-fuzz"
version.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
stratamoto-ir.workspace = true
stratamoto-scenarios.workspace = true
stratamoto.workspace = true
postcard.workspace = true
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "stratamoto-fuzz"
path = "src/main.rs"
