[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
async-channel = "2.5.0"
async-task = "4.7.1"
bytes = "1.11.1"
futures = "0.3.32"
log = "0.4.29"
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
stratum-core = "0.5.1"

env_logger = "0.11.10"

deterministic-simulator = { path = "crates/deterministic-simulator" }
stratamoto-ir = { path = "crates/stratamoto-ir" }
