[package]
name = "stratamoto-scenarios"
version.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
stratamoto.workspace = true
stratamoto-ir.workspace = true
stratamoto-targets.workspace = true
postcard.workspace = true
env_logger.workspace = true
log.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "setup_connection"
path = "bin/setup_connection.rs"

[[bin]]
name = "pool_setup_connection"
path = "bin/pool_setup_connection.rs"
