[package]
name = "stratamoto"
version.workspace = true
edition.workspace = true
readme = "README.md"

[dependencies]
serde.workspace = true
stratamoto-ir.workspace = true
stratum-apps.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
bs58 = { version = "0.5", features = ["check"] }
