[package]
name = "stratamoto-targets"
version.workspace = true
edition.workspace = true

[dependencies]
stratamoto.workspace = true
pool_sv2.workspace = true
stratum-apps = { workspace = true, features = ["config"] }
tokio.workspace = true
log.workspace = true

[dev-dependencies]
stratamoto-ir.workspace = true
