[package]
name = "stratamoto-dst"
version.workspace = true
edition.workspace = true
readme = "README.md"

[features]
macros = ["dep:stratamoto-macros"]

[dependencies]
async-channel.workspace = true
async-task.workspace = true
bytes.workspace = true
futures.workspace = true
log.workspace = true
rand = { version = "0.8", features = ["small_rng"] }
stratamoto-macros = { workspace = true, optional = true }

[dev-dependencies]
env_logger.workspace = true
